In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv('insurance.csv')
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [ ]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [ ]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy', #same as log loss
              metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.fit(X_train_scaled,y_train,epochs=200)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 661ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - 

In [ ]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - accuracy: 0.5000 - loss: 0.6625


[0.6625320911407471, 0.5]

In [ ]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step


array([[0.7367507 ],
       [0.6874325 ],
       [0.50768214],
       [0.7050054 ],
       [0.7399616 ],
       [0.7586871 ]], dtype=float32)

In [ ]:
coef,interrupt=model.get_weights()
coef,interrupt

(array([[0.8310509 ],
        [0.82389647]], dtype=float32),
 array([-0.18534225], dtype=float32))

In [ ]:
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))

def prediction_function(age,affordability):
  weighted_sum=coef[0]*age + coef[1]*affordability + interrupt
  return sigmoid(weighted_sum)

In [ ]:
prediction_function(.18,1)

/tmp/ipython-input-1067710783.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.6874325428291997

In [ ]:
class mynn:
  def __init__(self):
   pass

  def fit(self,X,y,epochs,loss_threshold):
    self.w1,self.w2,self.bias=self.gradient_descent(X['age'],X['affordability'],y,epochs,loss_threshold)

  def gradient_descent(self,age,affordability,y_true,epochs,loss_thresold):
    w1=w2=1
    bias=0
    rate=0.5
    n=len(age)
    for i in range(epochs):
      weighted_sum=w1*age + w2*affordability + bias
      y_predicted=sigmoid_numpy(weighted_sum)
      loss=log_loss(y_true,y_predicted)
      w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
      w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
      bias_d=np.mean(y_predicted-y_true)
      w1=w1-rate*w1d
      w2=w2-rate*w2d
      bias=bias-rate*bias_d

      print(f'Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')
      if loss<=loss_thresold:
        break
    return w1,w2,bias

# Helper functions
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))

def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [ ]:
customModel=mynn()
customModel.fit(X_train_scaled,y_train,epochs=5,loss_threshold=0.4631)

KeyError: 'affordability'