In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from matplotlib import pyplot as plt
%matplotlib inline


In [ ]:
df=pd.read_csv('homeprices_banglore.csv')
df.head(5)


area  bedrooms   price
0  1056         2   39.07
1  2600         4  120.00
2  1440         3   62.00
3  1521         3   75.00
4  1200         2   51.00

In [ ]:
from sklearn import preprocessing
sx=preprocessing.MinMaxScaler()
sy=preprocessing.MinMaxScaler()

scaled_X=sx.fit_transform(df.drop('price',axis='columns'))
scaled_y=sx.fit_transform(df['price'].values.reshape(df.shape[0],1))

scaled_X



array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [ ]:
scaled_y.reshape(20,)

array([0.05237037, 0.65185185, 0.22222222, 0.31851852, 0.14074074,
       0.04444444, 0.76296296, 0.91111111, 0.13333333, 1.        ,
       0.37037037, 0.8       , 0.04444444, 0.05925926, 0.51111111,
       0.07407407, 0.11851852, 0.20740741, 0.51851852, 0.        ])

In [ ]:
np.random.permutation(20)# gives random values for batch gradient descent

array([12,  9, 18,  5,  8, 16,  7,  0, 15,  4, 14,  3, 11,  2,  6,  1, 17,
       10, 19, 13])

In [ ]:
def batch_gradient_descent(X,y_true,epochs=100,batch_size=5,learning_rate=0.05):

  number_of_features=X.shape[1]
  w=np.ones(shape=(number_of_features))
  b=0
  total_samples=X.shape[0]

  if batch_size>total_samples:
    batch_size=total_samples


    cost_list=[]
    epoch_list=[]

    num_batches=int(total_samples/batch_size)

    for i in range(epochs):
      random_indices=np.random.premutation(total_samples)








SyntaxError: incomplete input (ipython-input-1846796222.py, line 22)